// News app: world news (generated by worldEngine) and personal story ledger.

import { escapeHtml, card, emptyState } from './helpers.js';

export function render(container, { state, actions }) {
  const worldNews = actions.getRecentNews(12);
  const personal = state.player.storyLedger.slice(-12).reverse();

  container.innerHTML = `
    ${card(
      'World news',
      worldNews.length
        ? `<ul style="list-style:none;padding:0;margin:0;">${worldNews
            .map((n) => `<li class="list-item"><span>${escapeHtml(n.text)}</span><span class="text-dim text-small">${n.season} ${n.year}</span></li>`)
            .join('')}</ul>`
        : emptyState('No world news yet — end a quarter to let the world move.')
    )}
    ${card(
      'Personal story',
      personal.length
        ? `<ul style="list-style:none;padding:0;margin:0;">${personal
            .map((s) => `<li class="list-item"><span>${escapeHtml(s.text)}</span></li>`)
            .join('')}</ul>`
        : emptyState('Nothing recorded yet.')
    )}
  `;
}
